#!/bin/sh
set -e

if [ -x /usr/bin/gtk-update-icon-cache ]; then
    gtk-update-icon-cache -f -q /usr/share/icons/hicolor || true
fi

if [ -x /usr/bin/update-desktop-database ]; then
    update-desktop-database -q /usr/share/applications || true
fi

if [ -x /usr/bin/appstreamcli ]; then
    appstreamcli refresh-cache --force || true
fi

#DEBHELPER#
exit 0
